FROM node:20-alpine AS builder

WORKDIR /usr/src/app

COPY package*.json ./
COPY webpack.config.js ./

RUN npm install
COPY . .

RUN npm run build


FROM node:20-alpine
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/dist ./dist
EXPOSE PORT_NUMBER
CMD ["node", "./dist/server.js"]
