version: '3'

services:
  sos-backend:
    container_name: sos-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "PORT:PORT"
    restart: always
    env_file:
      - ./.env
